import React, { useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";

// ----------------- ZOD VALIDATION SCHEMA -----------------
const formSchema = z.object({
  collegeName: z.string().min(2, "College name is required"),
  collegeCode: z
    .string()
    .min(2, "College code is required")
    .regex(/^[A-Z0-9-]+$/, "Only uppercase letters, numbers, and hyphens allowed"),
  aisheCode: z
    .string()
    .min(2, "AISHE code is required")
    .regex(/^[A-Z]-\d{4,}$/, "Invalid AISHE code format (e.g., U-1234)"),
  institutionType: z.string().min(1, "Select institution type"),
  address: z.string().min(5, "Address is required"),
  phone: z
    .string()
    .min(10, "Phone must be 10 digits")
    .max(10, "Phone must be exactly 10 digits"),
  stamp: z
    .any()
    .refine((file) => file?.length === 1, "Upload college stamp (JPEG only)")
    .refine(
      (file) => file && ["image/jpeg", "image/jpg"].includes(file[0]?.type),
      "Only JPEG format allowed"
    ),
});

// ----------------- COMPONENT -----------------
export default function CollegeForm() {
  const [stampName, setStampName] = useState("");

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm({
    resolver: zodResolver(formSchema),
  });

  const onSubmit = (data) => {
    const prepared = {
      ...data,
      stampFile: data.stamp[0],
    };
    console.log("College Registered:", prepared);
  };

  return (
    <div className="w-full min-h-screen flex justify-center items-center bg-green-100 px-4">
      <form
        onSubmit={handleSubmit(onSubmit)}
        className="w-full max-w-lg bg-white p-8 rounded-2xl shadow-lg"
      >
        {/* Heading */}
        <h1 className="font-poppins font-bold text-[28px] text-[#2C3E50] mb-1">
          Register a College
        </h1>
        <p className="font-poppins text-[16px] text-black/70 mb-6">
          IQAC Admin — Add a verified institution to the system.
        </p>

        {/* College Name */}
        <label className="block font-roboto text-[16px]">College Name</label>
        <input
          {...register("collegeName")}
          type="text"
          className="w-full mt-1 p-3 border border-gray-400 rounded-lg
                     focus:outline-none focus:ring-2 focus:ring-[#2C3E50]"
        />
        {errors.collegeName && (
          <p className="text-red-600 text-sm mt-1">{errors.collegeName.message}</p>
        )}

        {/* College Code (ADDED) */}
        <label className="block mt-4 font-roboto text-[16px]">College Code (Generated by Admin)</label>
        <input
          {...register("collegeCode")}
          type="text"
          placeholder="e.g., CLG-2025-OD"
          className="w-full mt-1 p-3 border border-gray-400 rounded-lg
                     uppercase focus:outline-none focus:ring-2 focus:ring-[#2C3E50]"
        />
        {errors.collegeCode && (
          <p className="text-red-600 text-sm mt-1">{errors.collegeCode.message}</p>
        )}

        {/* AISHE Code */}
        <label className="block mt-4 font-roboto text-[16px]">AISHE Code</label>
        <input
          {...register("aisheCode")}
          type="text"
          placeholder="e.g., U-1234"
          className="w-full mt-1 p-3 border border-gray-400 rounded-lg 
                     focus:outline-none focus:ring-2 focus:ring-[#2C3E50]"
        />
        {errors.aisheCode && (
          <p className="text-red-600 text-sm mt-1">{errors.aisheCode.message}</p>
        )}

        {/* Institution Type */}
        <label className="block mt-4 font-roboto text-[16px]">Institution Type</label>
        <select
          {...register("institutionType")}
          className="w-full mt-1 p-3 border border-gray-400 rounded-lg 
                     focus:outline-none focus:ring-2 focus:ring-[#2C3E50]"
        >
          <option value="">Select Type</option>
          <option value="Government">Government</option>
          <option value="Private">Private</option>
          <option value="Autonomous">Autonomous</option>
          <option value="Deemed">Deemed University</option>
        </select>
        {errors.institutionType && (
          <p className="text-red-600 text-sm mt-1">{errors.institutionType.message}</p>
        )}

        {/* Address */}
        <label className="block mt-4 font-roboto text-[16px]">Address</label>
        <textarea
          {...register("address")}
          className="w-full mt-1 p-3 border border-gray-400 rounded-lg h-24
                     focus:outline-none focus:ring-2 focus:ring-[#2C3E50]"
        />
        {errors.address && (
          <p className="text-red-600 text-sm mt-1">{errors.address.message}</p>
        )}

        {/* Phone Number */}
        <label className="block mt-4 font-roboto text-[16px]">College Phone Number</label>
        <input
          {...register("phone")}
          type="text"
          placeholder="10-digit number"
          className="w-full mt-1 p-3 border border-gray-400 rounded-lg 
                     focus:outline-none focus:ring-2 focus:ring-[#2C3E50]"
        />
        {errors.phone && (
          <p className="text-red-600 text-sm mt-1">{errors.phone.message}</p>
        )}

        {/* College Stamp Upload */}
        <label className="block mt-4 font-roboto text-[16px]">College Stamp (JPEG Only)</label>
        <input
          {...register("stamp")}
          type="file"
          accept=".jpeg,.jpg"
          onChange={(e) => setStampName(e.target.files[0]?.name || "")}
          className="w-full mt-1 p-3 border border-gray-400 rounded-lg 
                     bg-white cursor-pointer focus:outline-none focus:ring-2
                     focus:ring-[#2C3E50]"
        />
        {stampName && (
          <p className="text-sm text-gray-700 mt-1">Selected: {stampName}</p>
        )}
        {errors.stamp && (
          <p className="text-red-600 text-sm mt-1">{errors.stamp.message}</p>
        )}

        {/* Submit Button */}
        <button
          type="submit"
          className="w-full mt-6 py-3 bg-[#6C8F5E] text-white 
                     font-poppins font-semibold text-[16px] rounded-lg 
                     hover:scale-[1.02] transition-all"
        >
          Register College
        </button>
      </form>
    </div>
  );
}
